commands:

  - type: sync
    repo: 'https://github.com/tarjoilija/zgen'
    dst:  "<%= get_var! :'zsh.custom_dir', type: :directory %>/plugins/zgen"
    only: f?zsh


elems:
  - src: ^(zshrc)$
    dst: "<%= get_var! :'zsh.zshrc_path', type: :file %>"
    only: f?zsh
